# Feature 1
name: electron-secure-defaults

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Extra Step
      - name: release?
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ridhwanc'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Step 3: Build the app
      - name: Build the app
        run: npm run build

      - name: Check contents
        run: ls -al

      # Feature 3
      # Step 4: Check for vulnerabilities
      - name: Install electronegativity
        run: npm install @doyensec/electronegativity -g
      - name: Check for high and/or critical vulnerabilities
        run: electronegativity -i dist/ -s medium

      # Step 4: Install electron-builder
      - name: Install electron-builder
        run: npm install electron-builder

     # Feature 4:
     # Step 6: Package Electron App
      - name: Build Electron App
        run: export GH_TOKEN=${{ secrets.ACCESS_TOKEN }} && npx electron-builder -mwl --x64

      - name: check contents again
        run: ls -al

      # Step 7 Zip Folder and Ready Release
      - name: Zip folder
        run: zip -r electron-secure-defaults.zip . -x ".git/*" ".github/*" "node_modules/*"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}

      # Step 4: Send out the email
      # - name: Send email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp-mail.outlook.com
      #     server_port: 587
      #     secure: true
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: Github Actions job result
      #     to: ridhwan.c@outlook.com
      #     from: Ridhwan Chowdhury
      #     body: |
      #       Build succeeded for electron-secure-defaults on branch $BUILD_BRANCH at $BUILD_TIME (SHA: $BUILD_SHA)
