name: electron-secure-defaults

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Build the app
      - name: Build the app
        run: npm run build

      - name: Build and release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

        # Step 4: Send out the email
      # - name: Send email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp-mail.outlook.com
      #     server_port: 587
      #     secure: true
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: Github Actions job result
      #     to: ridhwan.c@outlook.com
      #     from: Ridhwan Chowdhury
      #     body: |
      #       Build succeeded for electron-secure-defaults on branch $BUILD_BRANCH at $BUILD_TIME (SHA: $BUILD_SHA)

  vulnerabilities:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Check for vulnerabilities
        run: npm run electronegativity